apiVersion: v1
kind: ReplicationController
metadata:
 name: nginxpod
 namespace: test-cs
spec:
 replicas: 2
 selector:
   app: ready
 template:
   metadata:
    labels:
     app: ready
   spec:
    containers:
     - name: nginxpod
       image: nginx
       ports:
        - containerPort: 80
       livenessProbe:
        exec:
         command:
          - cat
          - /usr/share/nginx/html/index.html
        initialDelaySeconds: 10
        periodSeconds: 5
       readinessProbe:
        exec:
         command:
          - cat
          - /usr/share/nginx/html/index.html
        initialDelaySeconds: 15
        periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
 name: podservice
 namespace: test-cs
spec:
 type: ClusterIP
 selector:
  app: ready
 ports:
 - port: 8080
   targetPort: 80
